### ISSUE TITLE
Error On Install

### ISSUE THREAD

**Issue by nikhiljha** [n8henrie/node-rcswitch-gpiomem#1]
```
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.1.18-v7+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/nikhil/RcSwitch/node_modules/rcswitch-gpiomem
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! rcswitch-gpiomem@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rcswitch-gpiomem@0.3.0 install script.
npm ERR! This is most likely a problem with the rcswitch-gpiomem package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls rcswitch-gpiomem
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.1.18-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "rcswitch-gpiomem" "--save"
npm ERR! cwd /home/nikhil/RcSwitch
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/nikhil/RcSwitch/npm-debug.log
npm ERR! not ok code 0

```

This happens on node 0.10.29

I'll update to the latest node and try again, but note that this is the version that gets installed for people when they sudo apt-get install npm node

Edit: Same error on latest stable node, any ideas?

**Comment by nikhiljha** [comment]
Fixed, problem on my end.
If anyone else ever has the same error, it's because you need to NOT install node with the package manager. It won't update otherwise.

**Comment by n8henrie** [comment]
Interesting, thanks for the report.
